In [1]:
import pandas as pd

In [2]:
visits_data = {
    "CustomerID": ["C1", "C2", 'C3', 'C4', 'C5', 'C6'],
    "Visit_Count": [5, 3, 8, 2, 7, 4]
}

purchase_data = {
    "CustomerID": ["C3", 'C4', 'C5', 'C7'],
    "Purchase_Amount":[200, 150, 300, 250]
}

visit_df = pd.DataFrame(visits_data)
purchase_df = pd.DataFrame(purchase_data)

In [3]:
print("Visit data\n",visit_df,"\nPurchase data\n",purchase_df)

Visit data
   CustomerID  Visit_Count
0         C1            5
1         C2            3
2         C3            8
3         C4            2
4         C5            7
5         C6            4
Purchase data
   CustomerID  Purchase_Amount
0         C3              200
1         C4              150
2         C5              300
3         C7              250

In [4]:
common_df = pd.merge(visit_df, purchase_df, on="CustomerID", how="inner")
left_df = pd.merge(visit_df, purchase_df, on="CustomerID", how="left")
right_df = pd.merge(visit_df, purchase_df, on="CustomerID", how="right")

In [5]:
print("customers who visited and purchased: ")
common_df

customers who visited and purchased:

  CustomerID  Visit_Count  Purchase_Amount
0         C3            8              200
1         C4            2              150
2         C5            7              300

In [18]:
print("customers who only visited and did not purchase:\n")
non_buyers = left_df[left_df["Purchase_Amount"].isna()]
non_buyers

customers who only visited and did not purchase:

  CustomerID  Visit_Count  Purchase_Amount
0         C1            5              NaN
1         C2            3              NaN
5         C6            4              NaN

In [17]:
print("Customers who did not visit, but purchased:\n")
new_buyers = right_df[right_df["Visit_Count"].isna()]
new_buyers

Customers who did not visit, but purchased:

  CustomerID  Visit_Count  Purchase_Amount
3         C7          NaN              250

In [21]:
total_df = pd.merge(visit_df, purchase_df, on="CustomerID", how="outer")

In [22]:
len(total_df)

7

In [23]:
total_df

  CustomerID  Visit_Count  Purchase_Amount
0         C1          5.0              NaN
1         C2          3.0              NaN
2         C3          8.0            200.0
3         C4          2.0            150.0
4         C5          7.0            300.0
5         C6          4.0              NaN
6         C7          NaN            250.0

In [24]:
common_df

  CustomerID  Visit_Count  Purchase_Amount
0         C3            8              200
1         C4            2              150
2         C5            7              300

In [25]:
len(visit_df)

6

In [26]:
len(purchase_df)

4