In [1]:
import numpy as np
import pandas as pd

In [4]:
my_header = ['a', 'b', 'c']
my_index_out = ['G1']*3 + ['G2']*3
my_index_in = [1, 2, 3]*2
my_index_zipped = list(zip(my_index_out, my_index_in))
my_index = pd.MultiIndex.from_tuples(my_index_zipped)
df2 = pd.DataFrame(data=np.random.randn(6, 3), index=my_index, columns=my_header)

In [5]:
df2

             a         b         c
G1 1 -0.188279 -0.349431 -0.145049
   2 -0.958083  0.130428  0.429133
   3 -0.280894 -0.102311 -0.463444
G2 1  1.385353  1.881011 -0.126022
   2  0.912856 -1.302533  0.406222
   3 -0.611254 -1.258095  0.479597

In [6]:
df = pd.read_csv('data_vals.csv')

In [10]:
df.head(3)

             Name Gender  Age  Grade Absence Bloodtype  Height  Weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [20]:
df.groupby(['Gender', 'Bloodtype'])['Height'].mean()

Gender  Bloodtype
F       A            172.450000
        AB           170.100000
        B            158.200000
        O            164.433333
M       A            165.700000
        AB           181.050000
        B            174.550000
        O            166.200000
Name: Height, dtype: float64

In [21]:
my_dict = {
    'Size': ['L']*2 + ['M']*3 + ['S']*4,
    'Type': ['A']*3 + ['B']*2 + ['A']*2 + ['B']*2,
    'Location': ['L1']*3 + ['L2']*2 + ['L1', 'L2', 'L2', 'L1'],
    'A': [1, 2, 2, 3, 3, 4, 5, 6, 7],
    'B': [2, 4, 5, 5, 6, 6, 8, 9, 9]
}

In [23]:
df = pd.DataFrame(my_dict)

In [24]:
df

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [26]:
dfr = pd.pivot_table(df, index=['Size', 'Type'], columns='Location', values='B')

In [27]:
dfr

Location    L1   L2
Size Type
L    A     3.0  NaN
M    A     5.0  NaN
     B     NaN  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [28]:
pd.pivot_table(df, index=['Size', 'Type'], columns='Location', values='B', fill_value=0)

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [38]:
pd.pivot_table(df, index=['Size', 'Type'], columns='Location', values='B', aggfunc='mean', fill_value=0)

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [53]:
pd.pivot_table(df, index=['Size', 'Type'], values=['A','B'], aggfunc='mean')

             A    B
Size Type
L    A     1.5  3.0
M    A     2.0  5.0
     B     3.0  5.5
S    A     4.5  7.0
     B     6.5  9.0

In [56]:
df.groupby(['Size', 'Type'])[['A', 'B']].median()

             A    B
Size Type
L    A     1.5  3.0
M    A     2.0  5.0
     B     3.0  5.5
S    A     4.5  7.0
     B     6.5  9.0

In [59]:
pd.pivot_table(df, index=['Size', 'Type'], columns='Location', values=['A','B'], aggfunc={'A':'max', 'B': 'min'})

             A         B
Location    L1   L2   L1   L2
Size Type
L    A     2.0  NaN  2.0  NaN
M    A     2.0  NaN  5.0  NaN
     B     NaN  3.0  NaN  5.0
S    A     4.0  5.0  6.0  8.0
     B     7.0  6.0  9.0  9.0