In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    'name': ['hongildong', 'hongeeedong', 'hongsamdong'],
    'math': [90, 80, 70],
    'eng': [98, 89, 95],
    'music': [85, 95, 100],
    'phys_tra': [100, 90, 90]
})

In [3]:
df

          name  math  eng  music  phys_tra
0   hongildong    90   98     85       100
1  hongeeedong    80   89     95        90
2  hongsamdong    70   95    100        90

In [4]:
df.set_index('name', inplace=True)

In [5]:
df.index

Index(['hongildong', 'hongeeedong', 'hongsamdong'], dtype='object', name='name')

In [6]:
df

             math  eng  music  phys_tra
name
hongildong     90   98     85       100
hongeeedong    80   89     95        90
hongsamdong    70   95    100        90

In [7]:
df.iloc[0]

math         90
eng          98
music        85
phys_tra    100
Name: hongildong, dtype: int64

In [8]:
df.iloc[[0]]

            math  eng  music  phys_tra
name
hongildong    90   98     85       100

In [9]:
c = df.loc['hongildong', ['math', 'music']]

In [11]:
c

math     90
music    85
Name: hongildong, dtype: int64

In [12]:
df.iloc[0, [2, 3]]

music        85
phys_tra    100
Name: hongildong, dtype: int64

In [16]:
df.iloc[0, [0, 2]]

math     90
music    85
Name: hongildong, dtype: int64

In [19]:
df.loc['hongildong', 'math':'phys_tra']

math         90
eng          98
music        85
phys_tra    100
Name: hongildong, dtype: int64

In [20]:
df.iloc[1, 1:]

eng         89
music       95
phys_tra    90
Name: hongeeedong, dtype: int64

In [23]:
df.iloc[1, 1:]

eng         89
music       95
phys_tra    90
Name: hongeeedong, dtype: int64

In [24]:
df.loc[['hongildong', 'hongeeedong'], ['music', 'phys_tra']]

             music  phys_tra
name
hongildong      85       100
hongeeedong     95        90

In [27]:
df.iloc[[1, 2], [1, 3]]

             eng  phys_tra
name
hongeeedong   89        90
hongsamdong   95        90

In [29]:
df.iloc[1:, 1:]

             eng  music  phys_tra
name
hongeeedong   89     95        90
hongsamdong   95    100        90

In [30]:
df['kor']=80

In [31]:
df

             math  eng  music  phys_tra  kor
name
hongildong     90   98     85       100   80
hongeeedong    80   89     95        90   80
hongsamdong    70   95    100        90   80

In [34]:
df.loc[df.index[1], 'kor'] = 95

In [35]:
df

             math  eng  music  phys_tra  kor
name
hongildong     90   98     85       100   80
hongeeedong    80   89     95        90   95
hongsamdong    70   95    100        90   80

In [36]:
df = df.reset_index()

In [37]:
df

          name  math  eng  music  phys_tra  kor
0   hongildong    90   98     85       100   80
1  hongeeedong    80   89     95        90   95
2  hongsamdong    70   95    100        90   80

In [38]:
df[3] = 0

In [39]:
df

          name  math  eng  music  phys_tra  kor  3
0   hongildong    90   98     85       100   80  0
1  hongeeedong    80   89     95        90   95  0
2  hongsamdong    70   95    100        90   80  0

In [40]:
df.set_index('name', inplace=True)

In [41]:
df

             math  eng  music  phys_tra  kor  3
name
hongildong     90   98     85       100   80  0
hongeeedong    80   89     95        90   95  0
hongsamdong    70   95    100        90   80  0

In [42]:
df[3] = 0

In [43]:
df

             math  eng  music  phys_tra  kor  3
name
hongildong     90   98     85       100   80  0
hongeeedong    80   89     95        90   95  0
hongsamdong    70   95    100        90   80  0

In [45]:
df.drop(3, axis=1, inplace=True)

In [46]:
df

             math  eng  music  phys_tra  kor
name
hongildong     90   98     85       100   80
hongeeedong    80   89     95        90   95
hongsamdong    70   95    100        90   80

In [47]:
df.loc[3] = 0

In [48]:
df

             math  eng  music  phys_tra  kor
name
hongildong     90   98     85       100   80
hongeeedong    80   89     95        90   95
hongsamdong    70   95    100        90   80
3               0    0      0         0    0

In [49]:
df.drop(3, axis=0, inplace=True)

In [50]:
df

             math  eng  music  phys_tra  kor
name
hongildong     90   98     85       100   80
hongeeedong    80   89     95        90   95
hongsamdong    70   95    100        90   80

In [61]:
df.index = ['stud1', 'stud2', 'stud3']

In [62]:
df

       math  eng  music  phys_tra  kor   name
stud1    90   98     85       100   80  stud1
stud2    80   89     95        90   95  stud2
stud3    70   95    100        90   80  stud3

In [63]:
dft = df.transpose()

In [64]:
dft

          stud1  stud2  stud3
math         90     80     70
eng          98     89     95
music        85     95    100
phys_tra    100     90     90
kor          80     95     80
name      stud1  stud2  stud3

In [66]:
dft.T

      math eng music phys_tra kor   name
stud1   90  98    85      100  80  stud1
stud2   80  89    95       90  95  stud2
stud3   70  95   100       90  80  stud3

In [79]:
dict_data = {f'c{i}':[3*i + k+1 for k in range(3)] for i in range(5)}

In [82]:
df2 = pd.DataFrame(dict_data)

In [84]:
df2.index = ['r1', 'r2', 'r3']

In [86]:
df2 = df2.reset_index()

In [87]:
df2

  index  c0  c1  c2  c3  c4
0    r1   1   4   7  10  13
1    r2   2   5   8  11  14
2    r3   3   6   9  12  15

In [88]:
df2 = df2.reset_index()

In [92]:
df2 = df2.drop('level_0', axis=1)

In [95]:
df2 = df2.set_index('index')

In [96]:
df2

       c0  c1  c2  c3  c4
index
r1      1   4   7  10  13
r2      2   5   8  11  14
r3      3   6   9  12  15

In [97]:
df2.sort_index()

       c0  c1  c2  c3  c4
index
r1      1   4   7  10  13
r2      2   5   8  11  14
r3      3   6   9  12  15

In [98]:
df2.sort_index(ascending=False)

       c0  c1  c2  c3  c4
index
r3      3   6   9  12  15
r2      2   5   8  11  14
r1      1   4   7  10  13

In [101]:
df2.sort_values(by='c2')

       c0  c1  c2  c3  c4
index
r1      1   4   7  10  13
r2      2   5   8  11  14
r3      3   6   9  12  15

In [102]:
student1 = pd.Series({'kor': 100, 'eng': 80, 'math': 90})

In [103]:
student1

kor     100
eng      80
math     90
dtype: int64

In [104]:
student1/100

kor     1.0
eng     0.8
math    0.9
dtype: float64

In [105]:
df

       math  eng  music  phys_tra  kor   name
stud1    90   98     85       100   80  stud1
stud2    80   89     95        90   95  stud2
stud3    70   95    100        90   80  stud3

In [131]:
student1 = df.iloc[0].drop('name')
student2 = df.iloc[1].drop('name')
student3 = df.iloc[2].drop('name')

In [132]:
student1 + student2

math        170
eng         187
music       180
phys_tra    190
kor         175
dtype: object

In [133]:
student3['music'] = np.nan

In [134]:
average = (student1 + student2 + student3)/3

In [135]:
average

math             80.0
eng              94.0
music             NaN
phys_tra    93.333333
kor              85.0
dtype: object

In [136]:
import seaborn as sns

In [137]:
titanic = sns.load_dataset('titanic')

In [138]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [141]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True