In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('./auto-mpg.csv')

In [9]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [10]:
miles_to_km = 1.60934 / 3.78541

df['kpl'] = df['mpg'] * miles_to_km

In [11]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kpl
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,7.652571
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,6.377143
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,7.652571
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,6.802286
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,7.227428
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl,11.478857
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup,18.706285
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage,13.604571
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger,11.904000
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10,13.179428

In [12]:
df['kpl'] = df['kpl'].round(2)

In [14]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kpl
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,7.65
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,6.80
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,7.23
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl,11.48
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup,18.71
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage,13.60
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger,11.90
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10,13.18

In [15]:
df.origin.unique()

array([1, 3, 2])

In [17]:
df['origin'].replace({1: 'USA', 2: 'EU', 3: 'JAPAN'}, inplace=True)

In [18]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kpl
0,18.0,8,307.0,130,3504,12.0,70,USA,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165,3693,11.5,70,USA,buick skylark 320,6.38
2,18.0,8,318.0,150,3436,11.0,70,USA,plymouth satellite,7.65
3,16.0,8,304.0,150,3433,12.0,70,USA,amc rebel sst,6.80
4,17.0,8,302.0,140,3449,10.5,70,USA,ford torino,7.23
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,USA,ford mustang gl,11.48
394,44.0,4,97.0,52,2130,24.6,82,EU,vw pickup,18.71
395,32.0,4,135.0,84,2295,11.6,82,USA,dodge rampage,13.60
396,28.0,4,120.0,79,2625,18.6,82,USA,ford ranger,11.90
397,31.0,4,119.0,82,2720,19.4,82,USA,chevy s-10,13.18

In [19]:
df['origin'] = df['origin'].astype('category')

In [20]:
df.dtypes

mpg              float64
cylinders          int64
displacement     float64
horsepower        object
weight             int64
acceleration     float64
model year         int64
origin          category
car name          object
kpl              float64
dtype: object

In [21]:
df['model year'] = df['model year'].astype('category')

In [24]:
df.horsepower.unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', nan, '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [25]:
df.dropna(subset=['horsepower'], axis=0, inplace=True)

In [26]:
df.horsepower.unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [27]:
df['horsepower'] = df['horsepower'].astype('float')

In [29]:
count, bin_dividers = np.histogram(df['horsepower'], bins=3)
print(bin_dividers)

[ 46.         107.33333333 168.66666667 230.        ]

In [30]:
bin_names = ['Low output', 'Normal Output', 'High Output']
df['hp_bin'] = pd.cut(x=df['horsepower'], bins=bin_dividers, labels=bin_names, include_lowest=True)

In [31]:
df[['horsepower', 'hp_bin']]

     horsepower         hp_bin
0         130.0  Normal Output
1         165.0  Normal Output
2         150.0  Normal Output
3         150.0  Normal Output
4         140.0  Normal Output
..          ...            ...
393        86.0     Low output
394        52.0     Low output
395        84.0     Low output
396        79.0     Low output
397        82.0     Low output

[392 rows x 2 columns]

In [32]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kpl,hp_bin
0,18.0,8,307.0,130.0,3504,12.0,70,USA,chevrolet chevelle malibu,7.65,Normal Output
1,15.0,8,350.0,165.0,3693,11.5,70,USA,buick skylark 320,6.38,Normal Output
2,18.0,8,318.0,150.0,3436,11.0,70,USA,plymouth satellite,7.65,Normal Output
3,16.0,8,304.0,150.0,3433,12.0,70,USA,amc rebel sst,6.80,Normal Output
4,17.0,8,302.0,140.0,3449,10.5,70,USA,ford torino,7.23,Normal Output
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,USA,ford mustang gl,11.48,Low output
394,44.0,4,97.0,52.0,2130,24.6,82,EU,vw pickup,18.71,Low output
395,32.0,4,135.0,84.0,2295,11.6,82,USA,dodge rampage,13.60,Low output
396,28.0,4,120.0,79.0,2625,18.6,82,USA,ford ranger,11.90,Low output
397,31.0,4,119.0,82.0,2720,19.4,82,USA,chevy s-10,13.18,Low output

In [33]:
df.head(20)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kpl,hp_bin
0,18.0,8,307.0,130.0,3504,12.0,70,USA,chevrolet chevelle malibu,7.65,Normal Output
1,15.0,8,350.0,165.0,3693,11.5,70,USA,buick skylark 320,6.38,Normal Output
2,18.0,8,318.0,150.0,3436,11.0,70,USA,plymouth satellite,7.65,Normal Output
3,16.0,8,304.0,150.0,3433,12.0,70,USA,amc rebel sst,6.80,Normal Output
4,17.0,8,302.0,140.0,3449,10.5,70,USA,ford torino,7.23,Normal Output
5,15.0,8,429.0,198.0,4341,10.0,70,USA,ford galaxie 500,6.38,High Output
6,14.0,8,454.0,220.0,4354,9.0,70,USA,chevrolet impala,5.95,High Output
7,14.0,8,440.0,215.0,4312,8.5,70,USA,plymouth fury iii,5.95,High Output
8,14.0,8,455.0,225.0,4425,10.0,70,USA,pontiac catalina,5.95,High Output
9,15.0,8,390.0,190.0,3850,8.5,70,USA,amc ambassador dpl,6.38,High Output
10,15.0,8,383.0,170.0,3563,10.0,70,USA,dodge challenger se,6.38,High Output
11,14.0,8,340.0,160.0,3609,8.0,70,USA,plymouth 'cuda 340,5.95,Normal Output
12,15.0,8,400.0,150.0,3761,9.5,70,USA,chevrolet monte carlo,6.38,Normal Output
13,14.0,8,455.0,225.0,3086,10.0,70,USA,buick estate wagon (sw),5.95,High Output
14,24.0,4,113.0,95.0,2372,15.0,70,JAPAN,toyota corona mark ii,10.20,Low output
15,22.0,6,198.0,95.0,2833,15.5,70,USA,plymouth duster,9.35,Low output
16,18.0,6,199.0,97.0,2774,15.5,70,USA,amc hornet,7.65,Low output
17,21.0,6,200.0,85.0,2587,16.0,70,USA,ford maverick,8.93,Low output
18,27.0,4,97.0,88.0,2130,14.5,70,JAPAN,datsun pl510,11.48,Low output
19,26.0,4,97.0,46.0,1835,20.5,70,EU,volkswagen 1131 deluxe sedan,11.05,Low output

In [34]:
df['horse_norm'] = df.horsepower/abs(df.horsepower.max())

In [35]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kpl,hp_bin,horse_norm
0,18.0,8,307.0,130.0,3504,12.0,70,USA,chevrolet chevelle malibu,7.65,Normal Output,0.565217
1,15.0,8,350.0,165.0,3693,11.5,70,USA,buick skylark 320,6.38,Normal Output,0.717391
2,18.0,8,318.0,150.0,3436,11.0,70,USA,plymouth satellite,7.65,Normal Output,0.652174
3,16.0,8,304.0,150.0,3433,12.0,70,USA,amc rebel sst,6.80,Normal Output,0.652174
4,17.0,8,302.0,140.0,3449,10.5,70,USA,ford torino,7.23,Normal Output,0.608696
...,...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,USA,ford mustang gl,11.48,Low output,0.373913
394,44.0,4,97.0,52.0,2130,24.6,82,EU,vw pickup,18.71,Low output,0.226087
395,32.0,4,135.0,84.0,2295,11.6,82,USA,dodge rampage,13.60,Low output,0.365217
396,28.0,4,120.0,79.0,2625,18.6,82,USA,ford ranger,11.90,Low output,0.343478
397,31.0,4,119.0,82.0,2720,19.4,82,USA,chevy s-10,13.18,Low output,0.356522

KeyError: "['horse_norm'] not found in axis"