In [6]:
import pandas as pd

df1 = pd.DataFrame({
    'Name': ['Hp', 'Db', 'Js', 'Jm', 'Jc'],
    'Gender': ['M', 'M', 'M', 'M', 'F'],
    'Age': [23, 31, 22, 36, 30]
})

print(df1)

  Name Gender  Age
0   Hp      M   23
1   Db      M   31
2   Js      M   22
3   Jm      M   36
4   Jc      F   30

In [7]:
df2 = pd.DataFrame({
    'Name':['Js','Adb','Jr','Jc'],
    'Position':['Intern','Team Lead','Manager','Manager'],
    'Wage':[25000,75000,90000,70000]
})
print(df2)

  Name   Position   Wage
0   Js     Intern  25000
1  Adb  Team Lead  75000
2   Jr    Manager  90000
3   Jc    Manager  70000

In [8]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None
) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    left : DataFrame or named Series
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
    on : label or list
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : label or list, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : label or list, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default True
        If False, avoid copy if possible.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

In [10]:
pd.merge(df1,df2,on='Name')

  Name Gender  Age Position   Wage
0   Js      M   22   Intern  25000
1   Jc      F   30  Manager  70000

In [11]:
pd.merge(df1,df2,left_on='Name',right_on='Name',how='inner')

  Name Gender  Age Position   Wage
0   Js      M   22   Intern  25000
1   Jc      F   30  Manager  70000

In [12]:
pd.merge(df1,df2,left_on='Name',right_on='Name',how='left')

  Name Gender  Age Position     Wage
0   Hp      M   23      NaN      NaN
1   Db      M   31      NaN      NaN
2   Js      M   22   Intern  25000.0
3   Jm      M   36      NaN      NaN
4   Jc      F   30  Manager  70000.0

In [13]:
pd.merge(df1,df2,left_on='Name',right_on='Name',how='right')

  Name Gender   Age   Position   Wage
0   Js      M  22.0     Intern  25000
1  Adb    NaN   NaN  Team Lead  75000
2   Jr    NaN   NaN    Manager  90000
3   Jc      F  30.0    Manager  70000

In [14]:
pd.merge(df1,df2,left_on='Name',right_on='Name',how='outer')

  Name Gender   Age   Position     Wage
0  Adb    NaN   NaN  Team Lead  75000.0
1   Db      M  31.0        NaN      NaN
2   Hp      M  23.0        NaN      NaN
3   Jc      F  30.0    Manager  70000.0
4   Jm      M  36.0        NaN      NaN
5   Jr    NaN   NaN    Manager  90000.0
6   Js      M  22.0     Intern  25000.0

In [15]:
help(pd.concat)

Help on function concat in module pandas.core.reshape.concat:

concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None
) -> 'DataFrame | Series'
    Concatenate pandas objects along a particular axis.

    Allows optional set logic along the other axes.

    Can also add a layer of hierarchical indexing on the concatenation axis,
    which may be useful if the labels are the same (or overlapping) on
    the passed axis number.

    Parameters
    ----------
    objs : a sequence or mapping of Series or DataFrame objects
        If a mapping is passed, the sorted keys will be used as the `keys`
        argument, unless it is passed, in which case the values will be
        selected (see below). Any None objects will be dropped silently unless
        they are all None in which case a ValueError will be raised.
    axis : {0/'index', 1/'columns'}, default 0
        The axis to concatenate along.
    join : {'inner', 'outer'}, default 'outer'
        How to handle indexes on other axis (or axes).
    ignore_index : bool, default False
        If True, do not use the index values along the concatenation axis. The
        resulting axis will be labeled 0, ..., n - 1. This is useful if you are
        concatenating objects where the concatenation axis does not have
        meaningful indexing information. Note the index values on the other
        axes are still respected in the join.
    keys : sequence, default None
        If multiple levels passed, should contain tuples. Construct
        hierarchical index using the passed keys as the outermost level.
    levels : list of sequences, default None
        Specific levels (unique values) to use for constructing a
        MultiIndex. Otherwise they will be inferred from the keys.
    names : list, default None
        Names for the levels in the resulting hierarchical index.
    verify_integrity : bool, default False
        Check whether the new concatenated axis contains duplicates. This can
        be very expensive relative to the actual data concatenation.
    sort : bool, default False
        Sort non-concatenation axis if it is not already aligned. One exception to
        this is when the non-concatentation axis is a DatetimeIndex and join='outer'
        and the axis is not already aligned. In that case, the non-concatenation
        axis is always sorted lexicographically.
    copy : bool, default True
        If False, do not copy data unnecessarily.

    Returns
    -------
    object, type of objs
        When concatenating all ``Series`` along the index (axis=0), a
        ``Series`` is returned. When ``objs`` contains at least one
        ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
        the columns (axis=1), a ``DataFrame`` is returned.

    See Also
    --------
    DataFrame.join : Join DataFrames using indexes.
    DataFrame.merge : Merge DataFrames by indexes or columns.

    Notes
    -----
    The keys, levels, and names arguments are all optional.

    A walkthrough of how this method fits in with other tools for combining
    pandas objects can be found `here
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

    It is not recommended to build DataFrames by adding single rows in a
    for loop. Build a list of rows and make a DataFrame in a single concat.

    Examples
    --------
    Combine two ``Series``.

    >>> s1 = pd.Series(['a', 'b'])
    >>> s2 = pd.Series(['c', 'd'])
    >>> pd.concat([s1, s2])
    0    a
    1    b
    0    c
    1    d
    dtype: object

    Clear the existing index and reset it in the result
    by setting the ``ignore_index`` option to ``True``.

    >>> pd.concat([s1, s2], ignore_index=True)
    0    a
    1    b
    2    c
    3    d
    dtype: object

    Add a hierarchical index at the outermost level of
    the data with the ``keys`` option.

    >>> pd.concat([s1, s2], keys=['s1', 's2'])
    s1  0    a
        1    b
    s2  0    c
        1    d
    dtype: object

    Label the index keys you create with the ``names`` option.

    >>> pd.concat([s1, s2], keys=['s1', 's2'],
    ...           names=['Series name', 'Row ID'])
    Series name  Row ID
    s1           0         a
                 1         b
    s2           0         c
                 1         d
    dtype: object

    Combine two ``DataFrame`` objects with identical columns.

    >>> df1 = pd.DataFrame([['a', 1], ['b', 2]],
    ...                    columns=['letter', 'number'])
    >>> df1
      letter  number
    0      a       1
    1      b       2
    >>> df2 = pd.DataFrame([['c', 3], ['d', 4]],
    ...                    columns=['letter', 'number'])
    >>> df2
      letter  number
    0      c       3
    1      d       4
    >>> pd.concat([df1, df2])
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects with overlapping columns
    and return everything. Columns outside the intersection will
    be filled with ``NaN`` values.

    >>> df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
    ...                    columns=['letter', 'number', 'animal'])
    >>> df3
      letter  number animal
    0      c       3    cat
    1      d       4    dog
    >>> pd.concat([df1, df3], sort=False)
      letter  number animal
    0      a       1    NaN
    1      b       2    NaN
    0      c       3    cat
    1      d       4    dog

    Combine ``DataFrame`` objects with overlapping columns
    and return only those that are shared by passing ``inner`` to
    the ``join`` keyword argument.

    >>> pd.concat([df1, df3], join="inner")
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects horizontally along the x axis by
    passing in ``axis=1``.

    >>> df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
    ...                    columns=['animal', 'name'])
    >>> pd.concat([df1, df4], axis=1)
      letter  number  animal    name
    0      a       1    bird   polly
    1      b       2  monkey  george

    Prevent the result from including duplicate index values with the
    ``verify_integrity`` option.

    >>> df5 = pd.DataFrame([1], index=['a'])
    >>> df5
       0
    a  1
    >>> df6 = pd.DataFrame([2], index=['a'])
    >>> df6
       0
    a  2
    >>> pd.concat([df5, df6], verify_integrity=True)
    Traceback (most recent call last):
        ...
    ValueError: Indexes have overlapping values: ['a']

    Append a single row to the end of a ``DataFrame`` object.

    >>> df7 = pd.DataFrame({'a': 1, 'b': 2}, index=[0])
    >>> df7
        a   b
    0   1   2
    >>> new_row = pd.Series({'a': 3, 'b': 4})
    >>> new_row
    a    3
    b    4
    dtype: int64
    >>> pd.concat([df7, new_row.to_frame().T], ignore_index=True)
        a   b
    0   1   2
    1   3   4

In [16]:
pd.concat([df1,df2],sort=True)

    Age Gender Name   Position     Wage
0  23.0      M   Hp        NaN      NaN
1  31.0      M   Db        NaN      NaN
2  22.0      M   Js        NaN      NaN
3  36.0      M   Jm        NaN      NaN
4  30.0      F   Jc        NaN      NaN
0   NaN    NaN   Js     Intern  25000.0
1   NaN    NaN  Adb  Team Lead  75000.0
2   NaN    NaN   Jr    Manager  90000.0
3   NaN    NaN   Jc    Manager  70000.0

In [17]:
pd.concat([df1,df2],axis=1,sort=True)

  Name Gender  Age Name   Position     Wage
0   Hp      M   23   Js     Intern  25000.0
1   Db      M   31  Adb  Team Lead  75000.0
2   Js      M   22   Jr    Manager  90000.0
3   Jm      M   36   Jc    Manager  70000.0
4   Jc      F   30  NaN        NaN      NaN

In [19]:
df1=pd.DataFrame({'a':['a0','a1','a2','a3'],
                  'b':['b0','b1','b2','b3'],
                  'c':['c0','c1','c2','c3']},
                 index=[0,1,2,3])
df1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [20]:
df2=pd.DataFrame({'a':['a2','a3','a4','a5'],
                  'b':['b2','b3','b4','b5'],
                  'c':['c2','c3','c4','c5'],
                  'd':['d2','d3','d4','d5']},
                 index=[2,3,4,5])
df2

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5

In [23]:
pd.concat([df1,df2],ignore_index=True)   #vertical

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
4  a2  b2  c2   d2
5  a3  b3  c3   d3
6  a4  b4  c4   d4
7  a5  b5  c5   d5

In [24]:
pd.concat([df1,df2],axis=1) #horizontal

     a    b    c    a    b    c    d
0   a0   b0   c0  NaN  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN  NaN
2   a2   b2   c2   a2   b2   c2   d2
3   a3   b3   c3   a3   b3   c3   d3
4  NaN  NaN  NaN   a4   b4   c4   d4
5  NaN  NaN  NaN   a5   b5   c5   d5

In [25]:
import pandas as pd

# Creating DataFrame
data = {
    "id": [128940, 130960, 138250, 139480, 142280],
    "stock_name": [
        "Hanmi Pharmaceutical",
        "CJ E&M",
        "NS Shopping",
        "E-mart",
        "Green Cross Medical Science Corporation"
    ],
    "value": [
        59385.666667,
        58540.666667,
        14558.666667,
        239230.833333,
        468.833333
    ],
    "price": [
        421000,
        98900,
        13200,
        254500,
        10200
    ]
}

df1 = pd.DataFrame(data)

# Display first 5 rows
print(df1.head())

       id                               stock_name          value   price
0  128940                     Hanmi Pharmaceutical   59385.666667  421000
1  130960                                   CJ E&M   58540.666667   98900
2  138250                              NS Shopping   14558.666667   13200
3  139480                                   E-mart  239230.833333  254500
4  142280  Green Cross Medical Science Corporation     468.833333   10200

In [28]:
df2=pd.read_excel('financial_dataset.xlsx')

In [29]:
df2

        id                     name           eps     bps        per       pbr
0   130960                   CJ E&M   6301.333333   54068  15.695091  1.829178
1   136480                Harim Co.    274.166667    3551  11.489362  0.887074
2   138040   Meritz Financial Group   2122.333333   14894   6.313806  0.899691
3   139480                   E-mart  18268.166667  295780  13.931338  0.860437
4   145990                  Samyang   5741.000000  108090  14.283226  0.758627
5   152330           Hyundai Motors   7210.500000  175300  10.245600  1.245600
6   161890                  LG Chem   8500.250000  220450  18.342100  2.134500
7   170450                 SK Hynix   9632.750000  134890   9.765432  1.567890
8   175620               Kakao Corp   4120.125000   45210  21.456700  3.245600
9   181200        Naver Corporation  10984.333333  198760  16.987654  2.876500
10  189340           POSCO Holdings   6782.666667  245600   8.765400  0.945600
11  193870          Kia Corporation   5330.875000  132540  12.456789  1.123400
12  198760                Celltrion   7421.500000  165430  14.987650  1.654300
13  205430  Doosan Heavy Industries   6895.250000  143200  11.654321  1.034500
14  210550      Samsung Electronics  12450.750000  310500  17.234560  2.456700

In [30]:
df1 = pd.read_excel('stock_dataset.xlsx')
df1

        id                               stock_name          value   price
0   128940                     Hanmi Pharmaceutical   59385.666667  421000
1   130960                                   CJ E&M   58540.666667   98900
2   138250                              NS Shopping   14558.666667   13200
3   139480                                   E-mart  239230.833333  254500
4   142280  Green Cross Medical Science Corporation     468.833333   10200
5   145990                      Samsung Electronics  315000.500000   70500
6   152330                           Hyundai Motors  142300.250000  189000
7   161890                                  LG Chem   89050.750000  620000
8   170450                                 SK Hynix  178400.125000  128000
9   175620                               Kakao Corp   96540.875000   54000
10  181200                        Naver Corporation  123450.500000  220000
11  189340                           POSCO Holdings   76540.250000  310000
12  193870                          Kia Corporation  110230.625000   87000
13  198760                                Celltrion  134560.750000  165000
14  205430                  Doosan Heavy Industries   84500.500000   99000

In [31]:
df1.head()

       id                               stock_name          value   price
0  128940                     Hanmi Pharmaceutical   59385.666667  421000
1  130960                                   CJ E&M   58540.666667   98900
2  138250                              NS Shopping   14558.666667   13200
3  139480                                   E-mart  239230.833333  254500
4  142280  Green Cross Medical Science Corporation     468.833333   10200

In [32]:
df2.head()

       id                    name           eps     bps        per       pbr
0  130960                  CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480               Harim Co.    274.166667    3551  11.489362  0.887074
2  138040  Meritz Financial Group   2122.333333   14894   6.313806  0.899691
3  139480                  E-mart  18268.166667  295780  13.931338  0.860437
4  145990                 Samyang   5741.000000  108090  14.283226  0.758627

In [33]:
pd.merge(df1,df2)

,id,stock_name,value,price,name,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068,15.695091,1.829178
1,139480,E-mart,239230.833333,254500,E-mart,18268.166667,295780,13.931338,0.860437
2,145990,Samsung Electronics,315000.500000,70500,Samyang,5741.000000,108090,14.283226,0.758627
3,152330,Hyundai Motors,142300.250000,189000,Hyundai Motors,7210.500000,175300,10.245600,1.245600
4,161890,LG Chem,89050.750000,620000,LG Chem,8500.250000,220450,18.342100,2.134500
5,170450,SK Hynix,178400.125000,128000,SK Hynix,9632.750000,134890,9.765432,1.567890
6,175620,Kakao Corp,96540.875000,54000,Kakao Corp,4120.125000,45210,21.456700,3.245600
7,181200,Naver Corporation,123450.500000,220000,Naver Corporation,10984.333333,198760,16.987654,2.876500
8,189340,POSCO Holdings,76540.250000,310000,POSCO Holdings,6782.666667,245600,8.765400,0.945600
9,193870,Kia Corporation,110230.625000,87000,Kia Corporation,5330.875000,132540,12.456789,1.123400
10,198760,Celltrion,134560.750000,165000,Celltrion,7421.500000,165430,14.987650,1.654300
11,205430,Doosan Heavy Industries,84500.500000,99000,Doosan Heavy Industries,6895.250000,143200,11.654321,1.034500